# Generated by Django 4.2.1 on 2023-06-26 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_mascot_name_alter_person_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('D', 'Domestico'), ('W', 'Silvestre')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.mascot')),
            ],
        ),
    ]
