# Generated by Django 4.2.1 on 2023-05-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.participant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='cellphone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
